name: Deploy .NET 9 App to Local IIS

on:
  push:
    branches:
      - main
      - imtiazpc
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.313'

    - name: Restore Packages
      run: dotnet restore .\GitHubCiCDTest\GitHubCiCDTest.csproj

    - name: Build Application
      run: dotnet build .\GitHubCiCDTest\GitHubCiCDTest.csproj --configuration Release --no-restore

    - name: Publish Application
      run: dotnet publish .\GitHubCiCDTest\GitHubCiCDTest.csproj --configuration Release --no-build --output .\publish

    - name: Stop IIS App Pool
      shell: powershell
      continue-on-error: true
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "githubPool"

      shell: powershell
      run: |
        Copy-Item ".\publish\*" "E:\Sites\MyWebSite" -Recurse -Force

    - name: Start IIS App Pool
      shell: powershell
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "githubPool"