name: Deploy .NET 9 App to Local IIS
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Packages
        shell: pwsh
        run: dotnet restore .\CiCD_Pipline_To_IIS_window_server\CiCD_Pipline_To_IIS_window_server.csproj

      - name: Build Application
        shell: pwsh
        run: dotnet build .\CiCD_Pipline_To_IIS_window_server\CiCD_Pipline_To_IIS_window_server.csproj --configuration Release --no-restore

      - name: Publish Application
        shell: pwsh
        run: dotnet publish .\CiCD_Pipline_To_IIS_window_server\CiCD_Pipline_To_IIS_window_server.csproj --configuration Release --no-build --output .\publish

      - name: Stop IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "githubPool"
          do {
            Start-Sleep -Seconds 1
            $state = (Get-WebAppPoolState -Name "githubPool").Value
          } while ($state -ne "Stopped")

      - name: Copy Files to IIS Website Folder
        shell: powershell
        run: |
          Copy-Item ".\publish\*" "E:\Sites\MyWebSite" -Recurse -Force

      - name: Start IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "githubPool"
